### ISSUE TITLE
keypoints onnx导出报错

### ISSUE THREAD

**Issue by zhangdengp** [jamjamjon/YOLOXY#3]
RuntimeError: The size of tensor a (17) must match the size of tensor b (34) at non-singleton dimension 4

**Comment by jamjamjon** [comment]
抱歉现在才回复，bug已经修改，但由于使用inplace操作，导致导出的ONNX结构不整洁，最近忙完会更新，或者你也可以自行修改Detect中的forward()。

**Comment by zhangdengp** [comment]
修改后onnx能够导出，但是 detect.py推理Onnx 模型时，报错AttributeError: 'DetectMultiBackend' object has no attribute 'nk'

**Comment by jamjamjon** [comment]
过些天会有新的版本。着急的话你重新写个onnx推理吧。
